name: aptus
description: Meet people to do sport with.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animator: 0.1.4
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^4.0.5555
  provider: ^4.0.5
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.0+1
  modal_progress_hud: ^0.1.3
  progress_hud: ^1.1.0
  cached_network_image:
  firebase_storage: ^3.1.3
  font_awesome_flutter: ^8.4.0
  flutter_datetime_picker:
  geoflutterfire: ^2.1.0
  geolocator: ^5.3.2+2
  i18n_extension:
  email_validator: ^1.0.0
  shared_preferences: ^0.5.6+3






dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto Light Italic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf
  assets:
    - assets/images/



