name: aptus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.0+2
  image: ^2.0.7
  animator: 0.1.4
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  timeago: 2.0.17
  google_sign_in: ^4.1.4
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.12.4
  modal_progress_hud: ^0.1.3
  progress_hud: ^1.1.0
  provider_architecture: ^1.0.3
  cached_network_image:
  firebase_storage: ^3.1.3
  rxdart: ^0.20.0
  font_awesome_flutter: ^8.4.0
  geolocator: ^3.0.1
  get_it: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
  assets:
    - assets/images/AptusP_G.png
    - assets/images/bleu_image.png
    - assets/images/Aptus_white.png
    - assets/images/icons8-google-48.png
    - assets/images/icons8-facebook-circled-48.png



